# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4d9005df2865b9cd3b7b5efb71f9c6469e01ab9d572efdbf5a1d015d76b55c9122cc1bb78e546e0ec04919cbaf1d491c354105c7751d7c325c3f8545f39f943

test:
  secret_key_base: cf8743921b108de654073731cd2d382a430f4ce6528856285d0b88355db9585b30a1111d3c960ff5ce70e7f8ab9826ade4d949fee63cb66c167b717386df1f91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
