menubar: false
toolbar: "bold,italic,underline,forecolor backcolor,|,fontselect  fontsizeselect,|,bullist,numlist,outdent,indent,|,alignleft, aligncenter, alignright,|,uploadimage,emoticons"
plugins:
  - link
  - uploadimage
  - emoticons
  - textcolor
browser_spellcheck: true
relative_urls: false
