require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ContactFromsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ContactFrom. As you add validations to ContactFrom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContactFromsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all contact_froms as @contact_froms" do
      contact_from = ContactFrom.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:contact_froms)).to eq([contact_from])
    end
  end

  describe "GET show" do
    it "assigns the requested contact_from as @contact_from" do
      contact_from = ContactFrom.create! valid_attributes
      get :show, {:id => contact_from.to_param}, valid_session
      expect(assigns(:contact_from)).to eq(contact_from)
    end
  end

  describe "GET new" do
    it "assigns a new contact_from as @contact_from" do
      get :new, {}, valid_session
      expect(assigns(:contact_from)).to be_a_new(ContactFrom)
    end
  end

  describe "GET edit" do
    it "assigns the requested contact_from as @contact_from" do
      contact_from = ContactFrom.create! valid_attributes
      get :edit, {:id => contact_from.to_param}, valid_session
      expect(assigns(:contact_from)).to eq(contact_from)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContactFrom" do
        expect {
          post :create, {:contact_from => valid_attributes}, valid_session
        }.to change(ContactFrom, :count).by(1)
      end

      it "assigns a newly created contact_from as @contact_from" do
        post :create, {:contact_from => valid_attributes}, valid_session
        expect(assigns(:contact_from)).to be_a(ContactFrom)
        expect(assigns(:contact_from)).to be_persisted
      end

      it "redirects to the created contact_from" do
        post :create, {:contact_from => valid_attributes}, valid_session
        expect(response).to redirect_to(ContactFrom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contact_from as @contact_from" do
        post :create, {:contact_from => invalid_attributes}, valid_session
        expect(assigns(:contact_from)).to be_a_new(ContactFrom)
      end

      it "re-renders the 'new' template" do
        post :create, {:contact_from => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contact_from" do
        contact_from = ContactFrom.create! valid_attributes
        put :update, {:id => contact_from.to_param, :contact_from => new_attributes}, valid_session
        contact_from.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested contact_from as @contact_from" do
        contact_from = ContactFrom.create! valid_attributes
        put :update, {:id => contact_from.to_param, :contact_from => valid_attributes}, valid_session
        expect(assigns(:contact_from)).to eq(contact_from)
      end

      it "redirects to the contact_from" do
        contact_from = ContactFrom.create! valid_attributes
        put :update, {:id => contact_from.to_param, :contact_from => valid_attributes}, valid_session
        expect(response).to redirect_to(contact_from)
      end
    end

    describe "with invalid params" do
      it "assigns the contact_from as @contact_from" do
        contact_from = ContactFrom.create! valid_attributes
        put :update, {:id => contact_from.to_param, :contact_from => invalid_attributes}, valid_session
        expect(assigns(:contact_from)).to eq(contact_from)
      end

      it "re-renders the 'edit' template" do
        contact_from = ContactFrom.create! valid_attributes
        put :update, {:id => contact_from.to_param, :contact_from => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contact_from" do
      contact_from = ContactFrom.create! valid_attributes
      expect {
        delete :destroy, {:id => contact_from.to_param}, valid_session
      }.to change(ContactFrom, :count).by(-1)
    end

    it "redirects to the contact_froms list" do
      contact_from = ContactFrom.create! valid_attributes
      delete :destroy, {:id => contact_from.to_param}, valid_session
      expect(response).to redirect_to(contact_froms_url)
    end
  end

end
